### ISSUE TITLE
Cursor is too big

### ISSUE THREAD

**Issue by vv221** [tton-bugs-hunters/tton-bug-tracker#1] opened 2017-03-03 10:30 UTC
From inXile forums:
[Cursor is too big](https://forums.inxile-entertainment.com/viewtopic.php?f=47&t=17190)

[comparative screenshots](https://forums.inxile-entertainment.com/viewtopic.php?f=47&t=17190#p181811)

Reported on multiple Linux distributions and Mac OS.
Might be a SDL bug, but that’s not confirmed yet.

**Comment by tonurics** [comment] 2017-03-03 19:30
This is a SDL bug. If I remember: it was caused by an upstream SDL patch to address very small cursors on high DPI screens.

There is a workaround being tested, but I'm not sure if it will make it into a patch. Ideally, SDL fixes it on their end.

**Comment by shmerl** [comment] 2017-03-03 19:31
@tonurics : Should we report it to SDL? I didn't find it in their bug tracker.

**Comment by tonurics** [comment] 2017-03-03 20:22
Hmm, I thought I originally read about it on their bug tracker... But I'm not finding it now. [This was a little while ago.]

**Comment by shmerl** [comment] 2017-03-26 17:20
So, should I open a new bug for SDL?

**Comment by unicyn** [comment] 2017-03-28 17:26
It seems to be fixed in 1.0.2 patch, but I cannot find nothing in the notes

**Comment by shmerl** [comment] 2017-03-28 17:29
I'll test a bit later today. I also don't see anything about in the changelog.

**Comment by tonurics** [comment] 2017-03-28 17:58
I didn't hear about any issues with the aforementioned workaround during testing. So it should be in the latest release [patch 1.0.2].

@shmerl: I'm pretty sure I saw the bug report on the SDL tracker originally. If it's not there now, I would assume it got cleared off for a reason...

**Closed** 2017-03-28 17:59 UTC
Labels: bug, Linux, MacOS, third-party

**Comment by shmerl** [comment] 2017-03-29 02:15
I just installed the update, and can confirm that cursor looks OK now.
