### ISSUE TITLE
Cosmetic behavior bug in inventory screen

### ISSUE THREAD

**Issue by Confusion** [tton-bugs-hunters/tton-bug-tracker#10] opened 2017-03-04 09:33 UTC
I obtained an artifact called 'The God of Small Devices' for Rhin. This adds +2 on max Cyphers. When I drag it to the appropriate slot in the inventory screen, the max number of Cyphers doesn't change and stays 3. When I subsequently remove it, it does change, from 3 to 5. When I then add it again, the max number of Cyphers reduces from 5 to 3. However, when I close the inventory with the artifact added to the slot (count show is 3) and open it again, the count is correct at 5.

Linux, Ubuntu 16.10, GoG

**Comment by vv221** [comment] 2017-03-04 11:04
Duplicate of #6

**Closed by vv221** 2017-03-04 11:04 UTC
Labels: duplicate
